"""首期种子数据：点位 / 图鉴 / 闯关 / 勋章。

幂等：仅当对应表为空时写入，可重复执行。
"""
from sqlalchemy import delete, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.models import (
    Activity,
    CommunityTopic,
    Favorite,
    Knowledge,
    LightMap,
    Medal,
    Quiz,
    QuizQuestion,
    Species,
    SpeciesPhoto,
    Spot,
)

# 已废弃的图鉴条目：早期用作「兜底泛称」，现在 AI 认不出会自己给答案，不再需要。
# 启动时会把这些条目连同相关的收藏/照片一起清掉。
DEPRECATED_SPECIES = ("sp_shore_crab", "sp_small_fish")

# ---- 临时下线开关（测试用）----
# 想临时从图鉴里隐藏某个物种，就把它的 id 加进这个元组，重启后端即可。
# 恢复时**只需把 id 从这里删掉**（SPECIES 里的条目不用动），重启后会自动重新出现。
HIDDEN_SPECIES: tuple[str, ...] = (
    "sp_korean_rockfish",  # 许氏平鲉：暂时下线，方便测试其他内容
)

SPOTS = [
    {
        "id": "spot_qd_shilaoren",
        "name": "青岛·石老人",
        "city": "青岛",
        "cover_key": "",
        "open_time": "全年开放（涨潮时部分礁石被淹）",
        "age_hint": "适合 6 岁以上，低龄需大人牵手",
        "safety_tags": ["礁石湿滑", "远离涨潮线", "穿防滑鞋"],
        "observe_hint": "退潮后礁石滩露出，留意石缝里的藤壶、牡蛎和小螃蟹。",
        "description": "石老人海水浴场旁有大片礁石与潮池，是观察潮间带生物的热门点位。",
        "gear_list": ["防滑鞋", "小水桶", "观察盒"],
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-01",
        "lat": 36.083,
        "lng": 120.468,
    },
    {
        "id": "spot_qd_yigong",
        "name": "青岛·第一海水浴场",
        "city": "青岛",
        "cover_key": "",
        "open_time": "每年 6-9 月开放游泳，其余季节可赶海",
        "age_hint": "适合全年龄，需家长陪同",
        "safety_tags": ["注意浪", "远离深水区", "防晒"],
        "observe_hint": "沙滩与浅水交界处常有寄居蟹和小鱼，浅水区能见到海藻。",
        "description": "青岛老牌海水浴场，沙滩平缓，适合初学者观察近岸生物。",
        "gear_list": ["小铲子", "水桶", "遮阳帽"],
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-01",
        "lat": 36.058,
        "lng": 120.347,
    },
    {
        "id": "spot_qd_luqinghe",
        "name": "青岛·流清河",
        "city": "青岛",
        "cover_key": "",
        "open_time": "全年开放（退潮时段最佳）",
        "age_hint": "适合 8 岁以上，礁石较多",
        "safety_tags": ["礁石湿滑", "远离涨潮线"],
        "observe_hint": "崂山脚下，水质清澈，礁石上覆盖着海藻与成片藤壶。",
        "description": "崂山南麓的海湾，人少水清，是观察海藻与贝类的安静去处。",
        "gear_list": ["防滑鞋", "观察盒"],
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-01",
        "lat": 36.111,
        "lng": 120.555,
    },
    {
        "id": "spot_wh_chengshantou",
        "name": "威海·成山头",
        "city": "威海",
        "cover_key": "",
        "open_time": "全年开放",
        "age_hint": "适合 8 岁以上，风大需防风",
        "safety_tags": ["注意风浪", "远离崖边"],
        "observe_hint": "崖下礁石区在退潮时露出，能看到海葵与海星。",
        "description": "中国大陆海岸线东端，礁石陡峭，是观察岩岸生物的特色点位。",
        "gear_list": ["防滑鞋", "防风外套"],
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-01",
        "lat": 37.385,
        "lng": 122.713,
    },
]

SPECIES = [
    {
        "id": "sp_barnacle",
        "name": "藤壶",
        "aka": ["海蛀子", "马牙"],
        "category": "shell",
        "cover_key": "",
        "summary": "牢牢长在礁石上的小贝壳，退潮后会露出，是礁石上的常住居民。",
        "look": "身体被一圈圈灰白色硬壳围住，中央有个小口，会探出羽毛状的小脚。",
        "habitat": "潮间带礁石、码头、船底",
        "observe_tip": "退潮后用放大镜看壳口，耐心等一会儿能看到它伸小脚滤食。",
        "safety_tip": "壳边缘锋利，别用手抠，容易划伤。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-01",
        "protected": False,
    },
    {
        "id": "sp_oyster",
        "name": "牡蛎",
        "aka": ["生蚝", "海蛎子"],
        "category": "shell",
        "cover_key": "",
        "summary": "紧贴礁石生长的贝类，壳粗糙坚硬，退潮时最容易看见。",
        "look": "外壳形状不规则，灰褐色，内部光滑有光泽。",
        "habitat": "潮间带礁石、岩石海岸",
        "observe_tip": "注意牡蛎壳上常常附着小藤壶，可以一并观察。",
        "safety_tip": "壳极锋利，近距离观察时别坐靠上去。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-01",
        "protected": False,
    },
    {
        "id": "sp_limpet",
        "name": "帽贝",
        "aka": ["笠贝", "小斗笠"],
        "category": "shell",
        "cover_key": "",
        "summary": "像一顶小斗笠扣在礁石上，会慢慢移动啃食海藻。",
        "look": "贝壳呈斗笠状，表面有放射纹，颜色随环境变化。",
        "habitat": "潮间带岩石表面",
        "observe_tip": "记住它的位置，过一会儿回来看看它是不是挪了地方。",
        "safety_tip": "不要去抠它，离开水它会受伤。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-01",
        "protected": False,
    },
    {
        "id": "sp_sea_lettuce",
        "name": "石莼",
        "aka": ["海白菜", "绿海藻"],
        "category": "algae",
        "cover_key": "",
        "summary": "薄薄的绿色海藻，退潮后像铺在礁石上的绿纱。",
        "look": "叶片薄而透明，鲜绿色，成片生长。",
        "habitat": "潮间带岩石、潮池",
        "observe_tip": "轻轻碰一下，感受它又滑又软，是很重要的海洋初级生产者。",
        "safety_tip": "表面湿滑，观察时踩稳了再动。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-01",
        "protected": False,
    },
    {
        "id": "sp_hermit_crab",
        "name": "寄居蟹",
        "aka": ["海居蟹", "借壳蟹"],
        "category": "crab",
        "cover_key": "",
        "summary": "背着小房子到处跑的螃蟹，会“借”空螺壳当自己的家。",
        "look": "前半身是螃蟹，尾部卷曲藏在捡来的螺壳里，走路时会伸出两只小钳子。",
        "habitat": "潮间带滩涂、礁石缝隙",
        "observe_tip": "安静蹲下看它怎么搬家、怎么换壳，特别有趣。",
        "safety_tip": "不要把它从壳里拽出来，会伤害它。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-01",
        "protected": False,
    },
    {
        "id": "sp_sea_anemone",
        "name": "海葵",
        "aka": ["海菊花"],
        "category": "other",
        "cover_key": "",
        "summary": "长得像花却不是花，会伸出触手捕食，潮池里常能见到。",
        "look": "身体圆筒状，顶端一圈软软的触手，像盛开的小花。",
        "habitat": "潮池、岩石缝隙",
        "observe_tip": "退潮后海葵会缩成小团，等水没过又会慢慢展开。",
        "safety_tip": "触手有粘性，别用手戳。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-01",
        "protected": False,
    },
    {
        "id": "sp_starfish",
        "name": "海星",
        "aka": ["星鱼"],
        "category": "other",
        "cover_key": "",
        "summary": "长着五条腕的海洋动物，能慢慢爬行，还会把胃吐出来吃东西。",
        "look": "身体扁平，通常有五条腕，颜色有橙、红、紫等。",
        "habitat": "潮间带礁石、滩涂",
        "observe_tip": "看看它腹面的小管足，那才是它“走路”的工具。",
        "safety_tip": "别把它捞出水面太久，会脱水。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-01",
        "protected": False,
    },
    {
        "id": "sp_korean_rockfish",
        "name": "许氏平鲉",
        "aka": ["黑头鱼", "黑鲪", "黑石鲈"],
        "category": "fish",
        "cover_key": "",
        "summary": "近岸礁石区常见的小鱼，幼鱼常出现在潮池和浅水里，长大后体色变深。",
        "look": "身体侧扁、头较大；幼鱼体侧青绿带金属光泽，布满细密斑点，眼睛大而亮。",
        "habitat": "近岸礁石区、潮池、海藻丛",
        "observe_tip": "幼鱼常停在礁石边或海藻间不动，从侧面安静观察就能看很久。",
        "safety_tip": "背鳍有硬棘会扎手，只用眼睛看，不要徒手抓。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-09-11",
        "protected": False,
    },
    # ===== 贝类 / 螺类 =====
    {
        "id": "sp_mussel",
        "name": "贻贝",
        "aka": ["海虹", "淡菜"],
        "category": "shell",
        "cover_key": "",
        "summary": "一串串长在礁石缝里的小黑壳，退潮后常成群出现。",
        "look": "壳黑褐色、尖长，常一簇簇用足丝牢牢系在礁石上。",
        "habitat": "潮间带礁石、码头桩基",
        "observe_tip": "看看它们靠什么把自己“拴”在石头上，别硬拽下来。",
        "safety_tip": "壳边锋利，观察时小心别划手。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-27",
        "protected": False,
    },
    {
        "id": "sp_clam",
        "name": "蛤蜊",
        "aka": ["花蛤", "沙蛤"],
        "category": "shell",
        "cover_key": "",
        "summary": "躲在沙滩里的小贝，退潮后能看见沙面上冒小气泡。",
        "look": "壳上有花纹，两片壳紧紧合在一起，埋在沙里只露一点点。",
        "habitat": "潮间带沙滩、泥沙地",
        "observe_tip": "看沙滩上冒小泡的小洞，下面可能就藏着它。",
        "safety_tip": "挖蛤蜊要在安全区域，注意别被碎壳划伤。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-27",
        "protected": False,
    },
    {
        "id": "sp_scallop",
        "name": "扇贝",
        "aka": ["海扇"],
        "category": "shell",
        "cover_key": "",
        "summary": "壳像一把小扇子，还会“啪”地一下喷水游走。",
        "look": "两片壳像打开的折扇，有放射状的棱纹。",
        "habitat": "浅海、潮下带沙滩",
        "observe_tip": "退潮后常能捡到空壳，对着光看有彩色光泽。",
        "safety_tip": "活的扇贝壳会突然闭合，别把手伸进去。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-27",
        "protected": False,
    },
    {
        "id": "sp_razor_clam",
        "name": "蛏子",
        "aka": ["竹蛏", "缢蛏"],
        "category": "shell",
        "cover_key": "",
        "summary": "长得像根细长的小竹管，会快速缩回沙洞里。",
        "look": "壳又长又薄，像一节小竹筒，表面光滑。",
        "habitat": "潮间带沙滩、泥沙滩",
        "observe_tip": "轻轻在洞口撒点盐，能看到它探出头又缩回去。",
        "safety_tip": "挖蛏子动作要轻，别破坏滩涂。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-27",
        "protected": False,
    },
    {
        "id": "sp_abalone",
        "name": "鲍鱼",
        "aka": ["九孔螺", "石决明"],
        "category": "shell",
        "cover_key": "",
        "summary": "像半只小碗扣在礁石上，是名贵的海味。",
        "look": "壳扁平、一侧有一排小孔，紧紧吸附在礁石上。",
        "habitat": "潮下带礁石、岩缝",
        "observe_tip": "它吸力很大，观察就好，别尝试抠下来。",
        "safety_tip": "野生鲍鱼多受保护，不要采集。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-27",
        "protected": False,
    },
    {
        "id": "sp_whelk",
        "name": "海螺",
        "aka": ["香螺", "脉红螺"],
        "category": "shell",
        "cover_key": "",
        "summary": "背着螺旋小房子，退潮后常藏在礁石下。",
        "look": "壳螺旋状、厚实，有的带花纹，壳口像小门。",
        "habitat": "潮间带礁石、泥沙底",
        "observe_tip": "翻看礁石下的海螺时，记得看完放回原处。",
        "safety_tip": "有些海螺可能有毒，不要用手直接摸壳内软体。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-27",
        "protected": False,
    },
    {
        "id": "sp_cowry",
        "name": "宝贝螺",
        "aka": ["宝贝", "子安贝"],
        "category": "shell",
        "cover_key": "",
        "summary": "壳光滑得像瓷器，古时候还当过钱用。",
        "look": "壳光滑油亮、有斑点或条纹，腹面有一条细细的口。",
        "habitat": "潮间带礁石、珊瑚礁区",
        "observe_tip": "捡到空壳可以放在耳边听，有海浪声。",
        "safety_tip": "活的宝贝螺别捡，它需要回海水里。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-27",
        "protected": False,
    },
    {
        "id": "sp_chiton",
        "name": "石鳖",
        "aka": ["海和尚", "铁甲鱼"],
        "category": "shell",
        "cover_key": "",
        "summary": "背上八块小甲板，像个小铁甲虫趴在礁石上。",
        "look": "身体扁椭圆，背上有八块壳板，边缘一圈软裙边。",
        "habitat": "潮间带礁石表面",
        "observe_tip": "它吸得很牢，轻轻碰它会缩成一团。",
        "safety_tip": "别硬抠，会伤到它。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-27",
        "protected": False,
    },
    {
        "id": "sp_moon_snail",
        "name": "玉螺",
        "aka": ["月亮螺"],
        "category": "shell",
        "cover_key": "",
        "summary": "壳圆鼓鼓像个月亮，会在沙里慢慢爬。",
        "look": "壳近球形、光滑，有的大有的小，颜色淡。",
        "habitat": "潮间带沙滩、泥沙底",
        "observe_tip": "沙滩上那种圆圆的沙盘是它产的卵，可以看看别破坏。",
        "safety_tip": "观察后把它放回湿润的沙里。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-27",
        "protected": False,
    },
    # ===== 蟹类 =====
    {
        "id": "sp_fiddler_crab",
        "name": "招潮蟹",
        "aka": ["海蟛蜞", "红螯蟹"],
        "category": "crab",
        "cover_key": "",
        "summary": "雄蟹有一只特别大的钳子，挥起来像在“招潮”。",
        "look": "雄蟹一只螯特别大，颜色鲜艳，另一只小小的。",
        "habitat": "泥滩、河口滩涂",
        "observe_tip": "站在远处看雄蟹挥大螯求偶，别追太近。",
        "safety_tip": "大螯会夹人，只看不抓。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-27",
        "protected": False,
    },
    {
        "id": "sp_ghost_crab",
        "name": "沙蟹",
        "aka": ["鬼蟹", "幽灵蟹"],
        "category": "crab",
        "cover_key": "",
        "summary": "沙滩上跑得飞快的小蟹，一眨眼就钻进洞里。",
        "look": "颜色和沙子很像，眼睛竖起来像两根小柱。",
        "habitat": "高潮带沙滩",
        "observe_tip": "傍晚它们最活跃，蹲下静看它们挖洞。",
        "safety_tip": "别追着踩，可能踩塌它们的洞。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-27",
        "protected": False,
    },
    {
        "id": "sp_rock_crab",
        "name": "石蟹",
        "aka": ["岩蟹", "石岩蟹"],
        "category": "crab",
        "cover_key": "",
        "summary": "躲在礁石缝里，壳硬邦邦像块小石头。",
        "look": "壳厚、颜色灰褐，钳子粗壮有力。",
        "habitat": "潮间带礁石缝隙",
        "observe_tip": "翻石头找它时，看完要把石头轻轻放回原位。",
        "safety_tip": "钳子有力，会夹手，别徒手抓。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-27",
        "protected": False,
    },
    {
        "id": "sp_swimming_crab",
        "name": "梭子蟹",
        "aka": ["三疣梭子蟹", "海蟹"],
        "category": "crab",
        "cover_key": "",
        "summary": "壳两头尖像梭子，最后一对脚是“船桨”。",
        "look": "壳呈梭形，两端尖，最后两条腿扁扁的像桨。",
        "habitat": "浅海、潮下带泥沙底",
        "observe_tip": "退潮时偶尔能在浅水边看到它游动。",
        "safety_tip": "它游得快也会夹人，观察保持距离。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-27",
        "protected": False,
    },
    # ===== 虾 / 节肢动物 =====
    {
        "id": "sp_mantis_shrimp",
        "name": "皮皮虾",
        "aka": ["虾蛄", "螳螂虾"],
        "category": "other",
        "cover_key": "",
        "summary": "不是虾也不是螳螂，一对“拳头”能打出超快的一击。",
        "look": "身体扁平多节，前肢像小锤子，眼睛能转。",
        "habitat": "潮间带泥沙底、浅海",
        "observe_tip": "看它怎么用前肢捕食，很厉害但别逗它。",
        "safety_tip": "前肢击打很疼，别用手抓。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-27",
        "protected": False,
    },
    {
        "id": "sp_prawn",
        "name": "对虾",
        "aka": ["中国对虾", "明虾"],
        "category": "other",
        "cover_key": "",
        "summary": "半透明的小虾，游起来一弓一弓地弹。",
        "look": "身体透明带淡青色，触须细长，多对脚。",
        "habitat": "浅海、潮间带水域",
        "observe_tip": "潮池里看到透明小虾就是它，静看它游泳。",
        "safety_tip": "别去捞，容易伤到它。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-27",
        "protected": False,
    },
    {
        "id": "sp_horseshoe_crab",
        "name": "中华鲎",
        "aka": ["鲎", "马蹄蟹"],
        "category": "other",
        "cover_key": "",
        "summary": "长得像古代武士的盾牌，是活化石，现在是保护动物。",
        "look": "身体像马蹄，拖着一条长长的剑尾。",
        "habitat": "近海沙滩、浅海泥底",
        "observe_tip": "请远远看看就好，它是国家保护动物。",
        "safety_tip": "保护动物，不要触碰、不要捡走。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-27",
        "protected": True,
    },
    # ===== 藻类 =====
    {
        "id": "sp_kelp",
        "name": "海带",
        "aka": ["昆布", "海带菜"],
        "category": "algae",
        "cover_key": "",
        "summary": "长长的大叶子海藻，是海底的“大森林”。",
        "look": "叶片又长又宽，褐绿色，有光泽。",
        "habitat": "潮下带礁石",
        "observe_tip": "退潮后海边漂来的海带可以看看，别捡回去煮。",
        "safety_tip": "海带表面滑，别踩上去。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-27",
        "protected": False,
    },
    {
        "id": "sp_wakame",
        "name": "裙带菜",
        "aka": ["海芥菜", "若布"],
        "category": "algae",
        "cover_key": "",
        "summary": "叶片带“小裙子边”，退潮后常挂在礁石上。",
        "look": "叶片中间有主脉，边缘皱皱的像裙摆。",
        "habitat": "潮间带下部、潮下带礁石",
        "observe_tip": "摸一摸它滑滑的，闻一闻有海腥味。",
        "safety_tip": "湿滑，踩稳了再观察。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-27",
        "protected": False,
    },
    {
        "id": "sp_laver",
        "name": "紫菜",
        "aka": ["海苔", "甘紫菜"],
        "category": "algae",
        "cover_key": "",
        "summary": "薄薄的一片紫红色海藻，晒干就是吃的海苔。",
        "look": "叶片薄如纸，紫红或褐紫，贴生在礁石上。",
        "habitat": "高潮带礁石",
        "observe_tip": "看它在阳光下泛着紫红光泽。",
        "safety_tip": "别在湿滑的礁石上乱跑。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-27",
        "protected": False,
    },
    {
        "id": "sp_sargassum",
        "name": "马尾藻",
        "aka": ["海蒿子", "海藻"],
        "category": "algae",
        "cover_key": "",
        "summary": "一串串长着“小气球”的海藻，漂在水里像小树。",
        "look": "枝干细长，长着许多小气囊和细叶。",
        "habitat": "潮间带礁石、浅海",
        "observe_tip": "捏一捏上面的小气囊，能帮它浮起来。",
        "safety_tip": "别缠绕在身上玩。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-27",
        "protected": False,
    },
    {
        "id": "sp_agar",
        "name": "石花菜",
        "aka": ["琼脂菜", "洋菜"],
        "category": "algae",
        "cover_key": "",
        "summary": "紫红色的细枝海藻，煮了会变成“果冻”。",
        "look": "枝条细密，紫红或暗红，一簇簇长在礁石上。",
        "habitat": "潮间带礁石",
        "observe_tip": "看看它密密麻麻的细枝，像小树枝。",
        "safety_tip": "别踩，礁石湿滑。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-27",
        "protected": False,
    },
    # ===== 鱼类 =====
    {
        "id": "sp_mudskipper",
        "name": "弹涂鱼",
        "aka": ["跳跳鱼", "泥猴"],
        "category": "fish",
        "cover_key": "",
        "summary": "会“走路”的鱼，退潮后在泥滩上蹦蹦跳跳。",
        "look": "眼睛鼓鼓长在头顶，胸鳍像小短腿。",
        "habitat": "泥滩、河口滩涂",
        "observe_tip": "远远看它用胸鳍“爬行”、竖背鳍争地盘。",
        "safety_tip": "别去追，滩涂很泥泞容易陷脚。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-27",
        "protected": False,
    },
    {
        "id": "sp_pufferfish",
        "name": "河豚",
        "aka": ["气泡鱼", "河鲀"],
        "category": "fish",
        "cover_key": "",
        "summary": "一生气就鼓成一个小球，但身上有毒不能碰。",
        "look": "身体圆鼓鼓，受惊会胀大，肚皮有尖刺。",
        "habitat": "近海、河口",
        "observe_tip": "潮池里偶尔能见到，看看就好。",
        "safety_tip": "河豚有剧毒，绝不能徒手抓或吃。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-27",
        "protected": False,
    },
    {
        "id": "sp_seahorse",
        "name": "海马",
        "aka": ["龙落子", "马头鱼"],
        "category": "fish",
        "cover_key": "",
        "summary": "头像小马，尾巴会卷着海藻，是国家保护动物。",
        "look": "头像马，身体直立，尾巴细长能卷。",
        "habitat": "浅海海草床、珊瑚礁",
        "observe_tip": "请远远看看，别打扰它。",
        "safety_tip": "保护动物，不要触碰、不要捞。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-27",
        "protected": True,
    },
    # ===== 其他无脊椎动物 =====
    {
        "id": "sp_sea_urchin",
        "name": "海胆",
        "aka": ["刺锅子", "海刺猬"],
        "category": "other",
        "cover_key": "",
        "summary": "浑身是刺的“小刺猬”，刺底下藏着好吃的黄。",
        "look": "圆球状，满身硬刺，有的紫色有的黑。",
        "habitat": "潮间带礁石缝、潮池",
        "observe_tip": "看它慢慢移动的刺，别用手碰。",
        "safety_tip": "刺很尖会扎人，千万别赤脚踩。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-27",
        "protected": False,
    },
    {
        "id": "sp_sea_cucumber",
        "name": "海参",
        "aka": ["海黄瓜", "刺参"],
        "category": "other",
        "cover_key": "",
        "summary": "软软的一条，慢慢在海底爬，一受惊会吐内脏。",
        "look": "身体圆柱形、软软的有肉刺，像根黄瓜。",
        "habitat": "潮下带礁石、泥沙底",
        "observe_tip": "它爬得特别慢，安静看就好。",
        "safety_tip": "别戳它，受惊吐内脏会伤身体。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-27",
        "protected": False,
    },
    {
        "id": "sp_jellyfish",
        "name": "海蜇",
        "aka": ["水母", "海月水母"],
        "category": "other",
        "cover_key": "",
        "summary": "透明的小伞在水里一张一合，触手会蜇人。",
        "look": "伞状半透明，下面垂着细长触手。",
        "habitat": "近海、浅海水域",
        "observe_tip": "漂到沙滩上的水母看看就行，别碰。",
        "safety_tip": "触手会蜇人，不要用手碰，死水母也蜇人。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-27",
        "protected": False,
    },
    {
        "id": "sp_sea_hare",
        "name": "海兔",
        "aka": ["雨虎", "海蛞蝓"],
        "category": "other",
        "cover_key": "",
        "summary": "软软滑滑像小兔子，一受惊会喷紫色“墨水”。",
        "look": "身体柔软无壳，头上有两对触角像兔耳朵。",
        "habitat": "潮间带海藻间",
        "observe_tip": "看它吃海藻的样子，特别可爱。",
        "safety_tip": "轻轻观察，别把它拎出水面。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-27",
        "protected": False,
    },
    {
        "id": "sp_nudibranch",
        "name": "海蛞蝓",
        "aka": ["海牛", "海兔蛞蝓"],
        "category": "other",
        "cover_key": "",
        "summary": "海底最会“穿花衣”的小精灵，五颜六色。",
        "look": "身体柔软、颜色鲜艳，背上有漂亮的突起。",
        "habitat": "潮间带礁石、海藻上",
        "observe_tip": "颜色越鲜艳越要远远看，别碰。",
        "safety_tip": "有些海蛞蝓有毒，别用手摸。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-27",
        "protected": False,
    },
    {
        "id": "sp_ragworm",
        "name": "沙蚕",
        "aka": ["海虫", "岩虫"],
        "category": "other",
        "cover_key": "",
        "summary": "藏在泥沙里的小蠕虫，是钓鱼的好饵料。",
        "look": "身体细长分节，两侧有细小的刚毛。",
        "habitat": "潮间带泥沙底、礁石下",
        "observe_tip": "翻沙子时看到它钻进去，动作很快。",
        "safety_tip": "别徒手抓，刚毛可能扎手。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-27",
        "protected": False,
    },
    {
        "id": "sp_sea_squirt",
        "name": "海鞘",
        "aka": ["海奶子", "被囊动物"],
        "category": "other",
        "cover_key": "",
        "summary": "长在礁石上的“小水袋”，一碰会喷出一股水。",
        "look": "像个小口袋，有进出水口，颜色各异。",
        "habitat": "潮间带礁石、码头桩基",
        "observe_tip": "轻轻碰一下，看它喷水，很有意思。",
        "safety_tip": "别用力捏，会伤到它。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-27",
        "protected": False,
    },
    {
        "id": "sp_octopus",
        "name": "章鱼",
        "aka": ["八爪鱼", "八带"],
        "category": "other",
        "cover_key": "",
        "summary": "八条腕的聪明家伙，会变色还会喷墨逃跑。",
        "look": "身体圆软，八条腕上有吸盘，眼睛很灵。",
        "habitat": "潮间带礁石缝、潮池",
        "observe_tip": "潮池里的小章鱼，静看它变色躲藏。",
        "safety_tip": "别抓，它会咬，也会喷墨。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-27",
        "protected": False,
    },
    {
        "id": "sp_cuttlefish",
        "name": "乌贼",
        "aka": ["墨鱼", "墨斗鱼"],
        "category": "other",
        "cover_key": "",
        "summary": "身体里藏一块白色“墨鱼骨”，会喷墨汁。",
        "look": "身体椭圆，两侧有鳍，肚里有白骨头。",
        "habitat": "浅海、近海",
        "observe_tip": "海边捡到的白色墨鱼骨，是它留下的。",
        "safety_tip": "观察为主，别打扰活的乌贼。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-27",
        "protected": False,
    },
    {
        "id": "sp_sand_dollar",
        "name": "海钱",
        "aka": ["沙币", "沙钱"],
        "category": "other",
        "cover_key": "",
        "summary": "扁扁圆圆的像枚硬币，是海胆的近亲。",
        "look": "身体扁平圆形，表面有五瓣花纹。",
        "habitat": "潮下带沙滩、浅海",
        "observe_tip": "捡到白色空壳可以看看上面的花纹。",
        "safety_tip": "活的海钱要放回海里。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-27",
        "protected": False,
    },
    {
        "id": "sp_sea_slater",
        "name": "海蟑螂",
        "aka": ["海虱", "海岸水虱"],
        "category": "other",
        "cover_key": "",
        "summary": "礁石缝里成群的小虫，跑得飞快，其实不是蟑螂。",
        "look": "身体扁平灰褐，有好多腿，受惊四散跑。",
        "habitat": "高潮带礁石缝、岩岸",
        "observe_tip": "看它们成群在礁石上找海藻吃。",
        "safety_tip": "不咬人，但别抓，它们会装死或乱跑。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-27",
        "protected": False,
    },
    {
        "id": "sp_blood_clam",
        "name": "毛蚶",
        "aka": ["血蛤", "毛蛤", "赤贝"],
        "category": "shell",
        "cover_key": "",
        "summary": "壳上长着细毛的小贝，煮熟会流“红汁”，是北方赶海的常见收获。",
        "look": "壳厚鼓鼓的，表面布满细密的毛状凸起，里面橘红色。",
        "habitat": "潮间带泥沙底、滩涂",
        "observe_tip": "退潮后沙滩上能看到半埋在沙里的毛蚶，轻轻拨开沙子找。",
        "safety_tip": "壳边的毛刺会扎手，捡的时候别太用力。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-28",
        "protected": False,
    },
    {
        "id": "sp_babylon_snail",
        "name": "花螺",
        "aka": ["东风螺", "黄螺"],
        "category": "shell",
        "cover_key": "",
        "summary": "壳上带漂亮斑纹的螺，常在浅滩慢慢爬行。",
        "look": "壳橄榄形，表面有黄褐色斑块花纹，壳口较大。",
        "habitat": "潮间带泥沙底、浅海",
        "observe_tip": "看它在沙面上留下的爬痕，能判断它往哪边去了。",
        "safety_tip": "别徒手摸壳内软体，有些螺可能有毒。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-28",
        "protected": False,
    },
    {
        "id": "sp_spoon_worm",
        "name": "海肠",
        "aka": ["单环刺螠", "海鸡子"],
        "category": "other",
        "cover_key": "",
        "summary": "长得像一根粉红色的“小香肠”，埋在海滩泥沙里。",
        "look": "身体圆柱形、粉红或肉色，前端有几根短须。",
        "habitat": "潮间带泥沙底、滩涂",
        "observe_tip": "用铲子轻轻挖滩涂，能看到它飞快缩回洞里。",
        "safety_tip": "挖的时候轻一点，别破坏滩涂。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-28",
        "protected": False,
    },
    {
        "id": "sp_goose_barnacle",
        "name": "狗爪螺",
        "aka": ["龟足", "佛手螺", "笔架"],
        "category": "shell",
        "cover_key": "",
        "summary": "像乌龟的小爪子一样扒在礁石上的甲壳动物，一簇簇生长。",
        "look": "顶端是几片灰白壳板，下面是黑褐色的软柄，成簇附在岩缝里。",
        "habitat": "潮间带礁石、岩缝",
        "observe_tip": "退潮后看它们一簇簇牢牢扒在礁石上，像小爪子。",
        "safety_tip": "壳边缘锋利，别硬抠，会划伤手。",
        "source": "追潮记团队整理",
        "reviewed_at": "2026-08-28",
        "protected": False,
    },
]

# 官方图鉴封面图对象 key（对应 data/uploads/pictorial/ 下的文件）
SPECIES_COVERS = {
    "sp_barnacle": "pictorial/sp_barnacle.jpg",
    "sp_oyster": "pictorial/sp_oyster.jpg",
    "sp_limpet": "pictorial/sp_limpet.jpg",
    "sp_sea_lettuce": "pictorial/sp_sea_lettuce.jpg",
    "sp_hermit_crab": "pictorial/sp_hermit_crab.gif",
    "sp_sea_anemone": "pictorial/sp_sea_anemone.jpg",
    "sp_starfish": "pictorial/sp_starfish.jpg",
    "sp_mussel": "pictorial/sp_mussel.jpg",
    "sp_clam": "pictorial/sp_clam.jpg",
    "sp_scallop": "pictorial/sp_scallop.jpg",
    "sp_razor_clam": "pictorial/sp_razor_clam.jpg",
    "sp_abalone": "pictorial/sp_abalone.jpg",
    "sp_whelk": "pictorial/sp_whelk.jpg",
    "sp_cowry": "pictorial/sp_cowry.jpg",
    "sp_chiton": "pictorial/sp_chiton.jpg",
    "sp_moon_snail": "pictorial/sp_moon_snail.jpg",
    "sp_fiddler_crab": "pictorial/sp_fiddler_crab.jpg",
    "sp_ghost_crab": "pictorial/sp_ghost_crab.jpg",
    "sp_rock_crab": "pictorial/sp_rock_crab.jpg",
    "sp_swimming_crab": "pictorial/sp_swimming_crab.jpg",
    "sp_mantis_shrimp": "pictorial/sp_mantis_shrimp.jpg",
    "sp_prawn": "pictorial/sp_prawn.jpg",
    "sp_horseshoe_crab": "pictorial/sp_horseshoe_crab.jpg",
    "sp_kelp": "pictorial/sp_kelp.jpg",
    "sp_wakame": "pictorial/sp_wakame.jpg",
    "sp_laver": "pictorial/sp_laver.jpg",
    "sp_sargassum": "pictorial/sp_sargassum.jpg",
    "sp_agar": "pictorial/sp_agar.jpg",
    "sp_mudskipper": "pictorial/sp_mudskipper.jpg",
    "sp_pufferfish": "pictorial/sp_pufferfish.jpg",
    "sp_seahorse": "pictorial/sp_seahorse.jpg",
    "sp_sea_urchin": "pictorial/sp_sea_urchin.jpg",
    "sp_sea_cucumber": "pictorial/sp_sea_cucumber.jpg",
    "sp_jellyfish": "pictorial/sp_jellyfish.jpg",
    "sp_sea_hare": "pictorial/sp_sea_hare.jpg",
    "sp_nudibranch": "pictorial/sp_nudibranch.jpg",
    "sp_ragworm": "pictorial/sp_ragworm.jpg",
    "sp_sea_squirt": "pictorial/sp_sea_squirt.jpg",
    "sp_octopus": "pictorial/sp_octopus.jpg",
    "sp_cuttlefish": "pictorial/sp_cuttlefish.jpg",
    "sp_sand_dollar": "pictorial/sp_sand_dollar.jpg",
    "sp_sea_slater": "pictorial/sp_sea_slater.jpg",
    "sp_blood_clam": "pictorial/sp_blood_clam.jpg",
    "sp_babylon_snail": "pictorial/sp_babylon_snail.jpg",
    "sp_spoon_worm": "pictorial/sp_spoon_worm.jpg",
    "sp_goose_barnacle": "pictorial/sp_goose_barnacle.jpg",
    "sp_korean_rockfish": "pictorial/sp_korean_rockfish.jpg",
}

QUIZZES = [
    {"id": "quiz_tide_intro", "title": "潮汐入门", "cover_key": ""},
    {"id": "quiz_intertidal", "title": "潮间带生物", "cover_key": ""},
    {"id": "quiz_safety", "title": "安全观察", "cover_key": ""},
]

QUIZ_QUESTIONS = [
    # 潮汐入门
    {
        "id": "qq_tide_1", "quiz_id": "quiz_tide_intro", "sort": 1,
        "stem": "退潮时，海水会向哪个方向退？",
        "options": [{"id": "A", "text": "向岸边涌来"}, {"id": "B", "text": "向海里退去"}, {"id": "C", "text": "原地不动"}],
        "correct_option_id": "B",
        "explain": "退潮时海水从岸边向海中退去，水位下降，露出潮间带。",
    },
    {
        "id": "qq_tide_2", "quiz_id": "quiz_tide_intro", "sort": 2,
        "stem": "一天里通常有几次涨潮、几次退潮？",
        "options": [{"id": "A", "text": "一次涨潮、一次退潮"}, {"id": "B", "text": "两次涨潮、两次退潮"}, {"id": "C", "text": "三次涨潮、三次退潮"}],
        "correct_option_id": "B",
        "explain": "大多数沿海地区一天有两次涨潮和两次退潮，约 12 小时一个周期。",
    },
    {
        "id": "qq_tide_3", "quiz_id": "quiz_tide_intro", "sort": 3,
        "stem": "下面哪个对地球潮汐的影响更大？",
        "options": [{"id": "A", "text": "月亮"}, {"id": "B", "text": "太阳"}, {"id": "C", "text": "星星"}],
        "correct_option_id": "A",
        "explain": "月亮离地球近，对潮汐的影响比太阳更大。",
    },
    {
        "id": "qq_tide_4", "quiz_id": "quiz_tide_intro", "sort": 4,
        "stem": "赶海观察潮间带生物，最好选在什么时候？",
        "options": [{"id": "A", "text": "涨潮最高的时候"}, {"id": "B", "text": "退潮后、涨潮前"}, {"id": "C", "text": "刮大风的时候"}],
        "correct_option_id": "B",
        "explain": "退潮后潮间带露出来，能看到更多生物，涨潮前又相对安全。",
    },
    {
        "id": "qq_tide_5", "quiz_id": "quiz_tide_intro", "sort": 5,
        "stem": "涨潮时，海边的水位会怎么样？",
        "options": [{"id": "A", "text": "升高，向岸边推进"}, {"id": "B", "text": "降低，向海里退"}, {"id": "C", "text": "保持不变"}],
        "correct_option_id": "A",
        "explain": "涨潮时海水向岸边推进，水位升高，会淹没潮间带。",
    },
    # 潮间带生物
    {
        "id": "qq_bi_1", "quiz_id": "quiz_intertidal", "sort": 1,
        "stem": "藤壶通常住在哪里？",
        "options": [{"id": "A", "text": "礁石表面"}, {"id": "B", "text": "大海深处"}, {"id": "C", "text": "天上"}],
        "correct_option_id": "A",
        "explain": "藤壶牢牢附着在潮间带的礁石、码头、船底上。",
    },
    {
        "id": "qq_bi_2", "quiz_id": "quiz_intertidal", "sort": 2,
        "stem": "寄居蟹的“家”是什么？",
        "options": [{"id": "A", "text": "自己盖的洞"}, {"id": "B", "text": "捡来的空螺壳"}, {"id": "C", "text": "树叶"}],
        "correct_option_id": "B",
        "explain": "寄居蟹会钻进空螺壳里当房子，长大了再换更大的壳。",
    },
    {
        "id": "qq_bi_3", "quiz_id": "quiz_intertidal", "sort": 3,
        "stem": "海葵是用什么来捕食的？",
        "options": [{"id": "A", "text": "触手"}, {"id": "B", "text": "脚"}, {"id": "C", "text": "翅膀"}],
        "correct_option_id": "A",
        "explain": "海葵伸出带黏性的触手，抓住路过的小浮游生物送进嘴里。",
    },
    {
        "id": "qq_bi_4", "quiz_id": "quiz_intertidal", "sort": 4,
        "stem": "观察潮间带生物时，下面哪种做法是对的？",
        "options": [{"id": "A", "text": "把它们抠下来带回家"}, {"id": "B", "text": "只用眼睛看，不伤害"}, {"id": "C", "text": "用棍子戳"}],
        "correct_option_id": "B",
        "explain": "观察生物要做到“只看不碰”，保护它们也保护自己。",
    },
    {
        "id": "qq_bi_5", "quiz_id": "quiz_intertidal", "sort": 5,
        "stem": "海星通常有几条腕？",
        "options": [{"id": "A", "text": "两条"}, {"id": "B", "text": "五条"}, {"id": "C", "text": "十条"}],
        "correct_option_id": "B",
        "explain": "大多数海星有五条腕，少数种类会更多。",
    },
    # 安全观察
    {
        "id": "qq_safe_1", "quiz_id": "quiz_safety", "sort": 1,
        "stem": "在湿滑的礁石上，下面哪种做法最安全？",
        "options": [{"id": "A", "text": "奔跑打闹"}, {"id": "B", "text": "站稳慢走，不奔跑"}, {"id": "C", "text": "光脚跳来跳去"}],
        "correct_option_id": "B",
        "explain": "礁石湿滑，要穿防滑鞋、站稳慢走，绝不奔跑。",
    },
    {
        "id": "qq_safe_2", "quiz_id": "quiz_safety", "sort": 2,
        "stem": "发现开始涨潮了，应该怎么做？",
        "options": [{"id": "A", "text": "继续玩"}, {"id": "B", "text": "提前离开水边"}, {"id": "C", "text": "往更深处走"}],
        "correct_option_id": "B",
        "explain": "涨潮很快，看到海水上涨要马上离开水边，回到安全的地方。",
    },
    {
        "id": "qq_safe_3", "quiz_id": "quiz_safety", "sort": 3,
        "stem": "遇到没见过的海洋生物，正确的做法是？",
        "options": [{"id": "A", "text": "远远看看，不碰"}, {"id": "B", "text": "抓起来研究"}, {"id": "C", "text": "用脚踩"}],
        "correct_option_id": "A",
        "explain": "不认识的生物可能有毒或会伤人，远远观察最安全。",
    },
    {
        "id": "qq_safe_4", "quiz_id": "quiz_safety", "sort": 4,
        "stem": "未成年人去赶海，最应该做到什么？",
        "options": [{"id": "A", "text": "有大人陪同"}, {"id": "B", "text": "自己去"}, {"id": "C", "text": "和小伙伴单独去"}],
        "correct_option_id": "A",
        "explain": "未成年人赶海一定要有大人陪同，安全第一。",
    },
]

_STATIC_BASE = "https://www.blueakaiwu.cn/api/v1/static/assets"

# 首页活动轮播（图片走静态资源同域，返回完整 URL）
# layout：card = 左侧文字 + 右侧小插图；banner = 整幅宽图铺满卡片
ACTIVITIES = [
    {
        "id": "act_deepblue_09",
        "tag": "科普",
        "title": "深蓝百万里",
        "desc": "探秘深海生物的世界",
        # theme=banner：前端把它渲染成「图片当背景 + 文字叠在上面」的横幅卡
        # （与前端同学上传的实现一致，不再用 layout 字段区分）
        "theme": "banner",
        "image": f"{_STATIC_BASE}/home/home-deepblue.png",
        # 站内页。原本想指向公众号文章，但 web-view 加载 mp.weixin.qq.com 需要
        # 「关联公众号」，真机过不了，已放弃外链方案。
        "url": "/pages/knowledge/knowledge",
        "sort": 0,
    },
    {
        "id": "act_science_09",
        "tag": "科普",
        "title": "潮间带科普课",
        "desc": "认识小螃蟹和贝类朋友",
        "theme": "teal",
        "image": f"{_STATIC_BASE}/home/home-fish.png",
        "url": "/pages/knowledge/knowledge",
        "sort": 1,
    },
    {
        "id": "act_study_09",
        "tag": "研学",
        "title": "赶海研学活动",
        "desc": "带上装备，一起去海边观察",
        "theme": "yellow",
        "image": f"{_STATIC_BASE}/home/home-nearby.png",
        "url": "/pages/spots/spots",
        "sort": 2,
    },
]

COMMUNITY_TOPICS = [
    {"id": "topic_lowtide", "name": "退潮观察", "sort": 1},
    {"id": "topic_rocky", "name": "礁石生物", "sort": 2},
    {"id": "topic_safety", "name": "安全赶海", "sort": 3},
    {"id": "topic_gear", "name": "装备分享", "sort": 4},
    {"id": "topic_wiki", "name": "图鉴对照", "sort": 5},
]

KNOWLEDGE = [
    {"id": "k_intertidal", "title": "潮间带是什么", "summary": "涨潮被淹、退潮露出来的那一带。", "tags": ["基础", "观察"], "sort": 1,
     "body": "潮间带是高潮线和低潮线之间的地带。涨潮时它在水下，退潮后石头、沙滩会露出来。很多小生物就住在这里，所以赶海观察，其实是在看潮间带的邻居。"},
    {"id": "k_ebb", "title": "为什么退潮更好观察", "summary": "水位下去，礁石缝更容易看见。", "tags": ["潮汐", "观察"], "sort": 2,
     "body": "退潮后水位降低，贴在礁石上的藤壶、牡蛎和潮沟里的小生物更容易被看见。不要等到涨潮再往水边走。看完要提前离开，给涨潮留出时间。"},
    {"id": "k_safety_rise", "title": "涨潮来了怎么办", "summary": "提前离开水边，不要贪看。", "tags": ["安全"], "sort": 3,
     "body": "潮水上涨比想象中快，尤其是礁石区。出门前先看今日高潮时间。如果水面明显上涨、浪花打到刚才还能走的地方，立刻往岸上走，不要回头捡东西。"},
    {"id": "k_slippery", "title": "礁石为什么湿滑", "summary": "海藻和湿石头会让脚打滑。", "tags": ["安全", "装备"], "sort": 4,
     "body": "礁石上常有海藻和积水，看起来不陡也会滑。穿防滑鞋，走稳再伸手看。不要奔跑，不要单脚踩尖石头。小朋友必须有大人牵着。"},
    {"id": "k_leave", "title": "看见了不要带走", "summary": "观察可以，把家搬回家不行。", "tags": ["保护", "观察"], "sort": 5,
     "body": "藤壶、海星、螺类都是潮间带的居民。把它们装进袋子，它们很难活下来，礁石上的邻居也会变少。用眼睛和图鉴对照就好，拍完照片把石头轻轻放回原处。"},
    {"id": "k_barnacle", "title": "礁石上的小房子", "summary": "那常常是藤壶，不是石头长出来的。", "tags": ["生物", "图鉴"], "sort": 6,
     "body": "退潮后礁石上密密的白色小房子，多半是藤壶。它们用壳粘在石头上滤食。不要用工具撬。对照图鉴看形状和排列，比凭感觉猜更准。"},
    {"id": "k_accompany", "title": "为什么要大人陪同", "summary": "海边有潮、有浪，也有湿滑。", "tags": ["安全", "适龄"], "sort": 7,
     "body": "赶海不是操场游戏。潮水、礁石和风浪都需要有人帮忙判断。小学中低年级请始终由大人陪同，不要独自走近水线。大人也要一起看潮汐时间。"},
    {"id": "k_gear", "title": "去海边带什么", "summary": "防滑、防晒、装水，比网兜更重要。", "tags": ["装备"], "sort": 8,
     "body": "优先带防滑鞋、防晒帽、饮用水和垃圾袋。小桶可以暂时盛一点海水观察，看完倒回海里。不推荐锋利工具。现场管理规定比装备清单更优先。"},
    {"id": "k_forecast", "title": "潮汐表只能当参考", "summary": "以海洋预报和现场警示为准。", "tags": ["潮汐", "安全"], "sort": 9,
     "body": "小程序里的潮高、涨退时间能帮你做计划，但不是保证。风力、风暴潮和景区封闭都会改变情况。出门前看官方预报，到了现场先看警示牌和工作人员指引。"},
    {"id": "k_observe", "title": "怎样才算认真观察", "summary": "蹲下来看，对照图鉴，记下时间。", "tags": ["观察", "图鉴"], "sort": 10,
     "body": "先看水位和安全，再选一块小范围慢慢看。记下大约时间、潮汐是涨还是退、生物长在石头上还是水洼里。不确定名字时，用拍照识别当线索，仍要打开图鉴再确认。"},
]

# 点亮地图：3 张图 × 6 个区块（map_url 留空，前端用本地底图）
LIGHT_MAPS = [
    {"id": "qingdao", "name": "青岛海岸", "map_url": "", "sort": 1, "regions": [
        {"id": "isles", "name": "离岛海域", "hint": "竹岔岛一带", "minLat": 35.96, "minLng": 120.30, "maxLat": 36.02, "maxLng": 120.38, "left": 0, "top": 0, "width": 34, "height": 52},
        {"id": "jiaozhou", "name": "胶州湾", "hint": "团岛到红岛沿岸", "minLat": 36.04, "minLng": 120.28, "maxLat": 36.16, "maxLng": 120.40, "left": 33, "top": 0, "width": 34, "height": 52},
        {"id": "qd_east", "name": "青岛东部海岸", "hint": "石老人到小麦岛一带", "minLat": 36.05, "minLng": 120.42, "maxLat": 36.12, "maxLng": 120.52, "left": 66, "top": 0, "width": 34, "height": 52},
        {"id": "west_coast", "name": "西海岸", "hint": "黄岛金沙滩一带", "minLat": 35.93, "minLng": 120.16, "maxLat": 36.02, "maxLng": 120.30, "left": 0, "top": 48, "width": 34, "height": 52},
        {"id": "jimo", "name": "即墨滨海", "hint": "鳌山卫到田横岛", "minLat": 36.32, "minLng": 120.62, "maxLat": 36.48, "maxLng": 120.80, "left": 33, "top": 48, "width": 34, "height": 52},
        {"id": "laoshan", "name": "崂山滨海", "hint": "崂山湾与仰口", "minLat": 36.12, "minLng": 120.54, "maxLat": 36.28, "maxLng": 120.72, "left": 66, "top": 48, "width": 34, "height": 52},
    ]},
    {"id": "weihai", "name": "威海海岸", "map_url": "", "sort": 2, "regions": [
        {"id": "liugong", "name": "刘公岛", "hint": "威海湾中的海岛", "minLat": 37.49, "minLng": 122.12, "maxLat": 37.52, "maxLng": 122.20, "left": 0, "top": 0, "width": 34, "height": 52},
        {"id": "weihai_bay", "name": "威海湾", "hint": "国际海水浴场一带", "minLat": 37.48, "minLng": 122.04, "maxLat": 37.54, "maxLng": 122.14, "left": 33, "top": 0, "width": 34, "height": 52},
        {"id": "chengshantou", "name": "成山头", "hint": "天尽头东端", "minLat": 37.36, "minLng": 122.52, "maxLat": 37.42, "maxLng": 122.72, "left": 66, "top": 0, "width": 34, "height": 52},
        {"id": "huancui", "name": "环翠沿岸", "hint": "市区海边栈道", "minLat": 37.50, "minLng": 121.98, "maxLat": 37.56, "maxLng": 122.08, "left": 0, "top": 48, "width": 34, "height": 52},
        {"id": "rongcheng", "name": "荣成滨海", "hint": "天鹅湖到东褚岛", "minLat": 37.32, "minLng": 122.40, "maxLat": 37.40, "maxLng": 122.55, "left": 33, "top": 48, "width": 34, "height": 52},
        {"id": "shidao", "name": "石岛", "hint": "南部渔港海岸", "minLat": 36.86, "minLng": 122.40, "maxLat": 36.94, "maxLng": 122.48, "left": 66, "top": 48, "width": 34, "height": 52},
    ]},
    {"id": "rizhao", "name": "日照海岸", "map_url": "", "sort": 3, "regions": [
        {"id": "wanpingkou", "name": "万平口", "hint": "市区黄金海岸", "minLat": 35.40, "minLng": 119.54, "maxLat": 35.46, "maxLng": 119.62, "left": 0, "top": 0, "width": 34, "height": 52},
        {"id": "lighthouse", "name": "灯塔风景区", "hint": "日照灯塔附近", "minLat": 35.38, "minLng": 119.52, "maxLat": 35.43, "maxLng": 119.58, "left": 33, "top": 0, "width": 34, "height": 52},
        {"id": "taigong", "name": "太公岛", "hint": "近岸小岛一带", "minLat": 35.36, "minLng": 119.56, "maxLat": 35.40, "maxLng": 119.62, "left": 66, "top": 0, "width": 34, "height": 52},
        {"id": "jiangfeng", "name": "姜太公故里岸", "hint": "北部沿海", "minLat": 35.48, "minLng": 119.50, "maxLat": 35.56, "maxLng": 119.62, "left": 0, "top": 48, "width": 34, "height": 52},
        {"id": "donggang", "name": "东港海岸", "hint": "港口以南沙滩", "minLat": 35.34, "minLng": 119.48, "maxLat": 35.40, "maxLng": 119.56, "left": 33, "top": 48, "width": 34, "height": 52},
        {"id": "lanshan", "name": "岚山滨海", "hint": "南部岚山沿岸", "minLat": 35.08, "minLng": 119.30, "maxLat": 35.18, "maxLng": 119.42, "left": 66, "top": 48, "width": 34, "height": 52},
    ]},
]

MEDALS = [
    {
        "id": "medal_1", "title": "初次见面", "display_title": "初来乍到", "rarity": "common",
        "icon_key": "", "description": "第一次生成属于你的图鉴卡。",
        "requirements": [{"text": "生成第一张图鉴卡"}], "rewards": {"score": 20}, "sort": 1,
    },
    {
        "id": "medal_2", "title": "探索新星", "display_title": "探索新星", "rarity": "rare",
        "icon_key": "", "description": "在 3 个不同点位完成打卡。",
        "requirements": [{"text": "打卡 3 个不同点位"}], "rewards": {"score": 50}, "sort": 2,
    },
    {
        "id": "medal_3", "title": "无畏冒险家", "display_title": "无畏冒险家", "rarity": "epic",
        "icon_key": "", "description": "完成「安全观察」闯关并全部答对。",
        "requirements": [{"text": "通过安全观察闯关"}], "rewards": {"score": 100}, "sort": 3,
    },
    {
        "id": "medal_4", "title": "宝藏猎人", "display_title": "宝藏猎人", "rarity": "rare",
        "icon_key": "", "description": "累计收集 5 张图鉴卡。",
        "requirements": [{"text": "收集 5 张图鉴卡"}], "rewards": {"score": 80}, "sort": 4,
    },
    {
        "id": "medal_5", "title": "解谜达人", "display_title": "解谜达人", "rarity": "epic",
        "icon_key": "", "description": "对照图鉴完成 3 次正确猜测。",
        "requirements": [{"text": "完成 3 次正确猜测"}], "rewards": {"score": 120}, "sort": 5,
    },
]


async def _seed_missing(session: AsyncSession, model, items: list[dict]) -> None:
    """按主键补齐缺失的种子数据（幂等，可重复执行，不覆盖已存在的行）。"""
    ids = [item["id"] for item in items]
    existing = set(
        (await session.execute(select(model.id).where(model.id.in_(ids)))).scalars().all()
    )
    missing = [item for item in items if item["id"] not in existing]
    if missing:
        session.add_all([model(**item) for item in missing])


async def _remove_deprecated_species(session: AsyncSession) -> None:
    """清理已废弃 / 临时下线的图鉴条目及其关联数据（幂等）。"""
    targets = tuple(DEPRECATED_SPECIES) + tuple(HIDDEN_SPECIES)
    if not targets:
        return
    await session.execute(
        delete(Favorite).where(
            Favorite.target_type == "species", Favorite.target_id.in_(targets)
        )
    )
    await session.execute(
        delete(SpeciesPhoto).where(SpeciesPhoto.species_id.in_(targets))
    )
    await session.execute(delete(Species).where(Species.id.in_(targets)))


async def _sync_team_source(session: AsyncSession) -> None:
    """把已有点位/图鉴的来源署名同步成最新团队名（幂等）。

    改名后旧行仍写着「观潮团队整理」，_seed_missing 只补新行不会改旧行，
    所以这里显式刷一遍。
    """
    for model in (Spot, Species):
        rows = (
            await session.execute(select(model).where(model.source == "观潮团队整理"))
        ).scalars().all()
        for row in rows:
            row.source = "追潮记团队整理"


async def _sync_species_covers(session: AsyncSession) -> None:
    """同步官方图鉴封面（幂等，覆盖旧值，保证新增与已存在的物种都带上图）。"""
    for species_id, cover_key in SPECIES_COVERS.items():
        species = await session.get(Species, species_id)
        if species is not None and species.cover_key != cover_key:
            species.cover_key = cover_key


SPOT_HEAT = {
    "spot_qd_shilaoren": 96,
    "spot_qd_yigong": 88,
    "spot_qd_luqinghe": 80,
    "spot_wh_chengshantou": 75,
}


async def _sync_spot_heat(session: AsyncSession) -> None:
    """同步点位热度（幂等，覆盖旧值）。"""
    for spot_id, heat in SPOT_HEAT.items():
        spot = await session.get(Spot, spot_id)
        if spot is not None:
            spot.heat = heat


async def seed_if_empty(session: AsyncSession) -> None:
    """按主键补齐种子数据（幂等）。表里已有的行不会被覆盖。"""
    await _seed_missing(session, Spot, SPOTS)
    await _sync_spot_heat(session)
    await _seed_missing(session, Species, SPECIES)
    await _remove_deprecated_species(session)
    await _sync_species_covers(session)
    await _sync_team_source(session)
    await _seed_missing(session, Quiz, QUIZZES)
    await _seed_missing(session, QuizQuestion, QUIZ_QUESTIONS)
    await _seed_missing(session, Medal, MEDALS)
    await _seed_missing(session, CommunityTopic, COMMUNITY_TOPICS)
    await _seed_missing(session, Knowledge, KNOWLEDGE)
    await _seed_missing(session, LightMap, LIGHT_MAPS)
    await _seed_missing(session, Activity, ACTIVITIES)
    await session.commit()
